
# Assignment 3 for Course 1MS041
Make sure you pass the `# ... Test` cells and
 submit your solution notebook in the corresponding assignment on the course website. You can submit multiple times before the deadline and your highest score will be used.

---
## Assignment 3, PROBLEM 1
Maximum Points = 8


Download the updated data folder from the course github website or just download directly the file [https://github.com/datascience-intro/1MS041-2024/blob/main/notebooks/data/smhi.csv](https://github.com/datascience-intro/1MS041-2024/blob/main/notebooks/data/smhi.csv) from the github website and put it inside your data folder, i.e. you want the path `data/smhi.csv`. The data was aquired from SMHI (Swedish Meteorological and Hydrological Institute) and constitutes per hour measurements of wind in the Uppsala Aut station. The data consists of windspeed and direction. Your goal is to load the data and work with it a bit. The code you produce should load the file as it is, please do not alter the file as the autograder will only have access to the original file.

The file information is in Swedish so you need to use some translation service, for instance `Google translate` or ChatGPT.

1. [2p] Load the file, for instance using the `csv` package. Put the wind-direction as a numpy array and the wind-speed as another numpy array.
2. [2p] Use the wind-direction which is an angle in degrees and convert it into a point on the unit circle. Store the `x_coordinate` as one array and the `y_coordinate` as another. From these coordinates, construct the wind-velocity vector.
3. [2p] Calculate the average wind velocity and convert it back to direction and compare it to just taking average of the wind direction as given in the data-file.
4. [2p] The wind velocity is a $2$-dimensional random variable, calculate the empirical covariance matrix which should be a numpy array of shape (2,2).

For you to wonder about, is it more likely for you to have headwind or not when going to the university in the morning.

In [1]:
import pandas as pd

df = pd.read_csv('data/smhi.csv', skiprows=11, delimiter=';')
df

Datum Tid (UTC)  Vindriktning Kvalitet  Vindhastighet Kvalitet.1  \
0     2024-06-27  01:00:00           348        G            0.6          G   
1     2024-06-27  02:00:00            43        G            0.2          G   
2     2024-06-27  03:00:00           185        G            0.1          G   
3     2024-06-27  04:00:00           126        G            0.8          G   
4     2024-06-27  05:00:00           130        G            0.7          G   
...          ...       ...           ...      ...            ...        ...   
3056  2024-11-04  01:00:00           276        G            1.9          G   
3057  2024-11-04  02:00:00           242        G            1.7          G   
3058  2024-11-04  03:00:00           269        G            1.6          G   
3059  2024-11-04  04:00:00           281        G            1.4          G   
3060  2024-11-04  05:00:00           252        G            1.4          G   

      Unnamed: 6                                      Tidsutsnitt:  
0            NaN                  Data från senaste fyra månaderna  
1            NaN  Tidsperiod (fr.o.m.) = 2024-06-27 00:00:01 (UTC)  
2            NaN   Tidsperiod (t.o.m.) = 2024-11-04 05:00:00 (UTC)  
3            NaN                         Samplingstid = 10 minuter  
4            NaN                                 Kvalitetskoderna:  
...          ...                                               ...  
3056         NaN                                               NaN  
3057         NaN                                               NaN  
3058         NaN                                               NaN  
3059         NaN                                               NaN  
3060         NaN                                               NaN  

[3061 rows x 8 columns]

In [2]:
data = df.T.head(5).T
data

Datum Tid (UTC) Vindriktning Kvalitet Vindhastighet
0     2024-06-27  01:00:00          348        G           0.6
1     2024-06-27  02:00:00           43        G           0.2
2     2024-06-27  03:00:00          185        G           0.1
3     2024-06-27  04:00:00          126        G           0.8
4     2024-06-27  05:00:00          130        G           0.7
...          ...       ...          ...      ...           ...
3056  2024-11-04  01:00:00          276        G           1.9
3057  2024-11-04  02:00:00          242        G           1.7
3058  2024-11-04  03:00:00          269        G           1.6
3059  2024-11-04  04:00:00          281        G           1.4
3060  2024-11-04  05:00:00          252        G           1.4

[3061 rows x 5 columns]

In [3]:
import numpy as np

problem1_wind_direction = np.array(data['Vindriktning'].astype('float'))
problem1_wind_speed = np.array(data['Vindhastighet'].astype('float'))

In [4]:
problem1_wind_direction

array([348.,  43., 185., ..., 269., 281., 252.], shape=(3061,))

In [5]:
problem1_wind_speed

array([0.6, 0.2, 0.1, ..., 1.6, 1.4, 1.4], shape=(3061,))

In [6]:
# The wind direction is given as a compass direction in degrees (0-360)
# convert it to x and y coordinates using the standard mathematical convention

problem1_wind_direction_x_coordinate = np.cos(np.radians(problem1_wind_direction))
problem1_wind_direction_y_coordinate = np.sin(np.radians(problem1_wind_direction))

problem1_wind_velocity_x_coordinate = problem1_wind_speed * problem1_wind_direction_x_coordinate
problem1_wind_velocity_y_coordinate = problem1_wind_speed * problem1_wind_direction_y_coordinate

In [7]:
print(problem1_wind_direction_x_coordinate, problem1_wind_direction_y_coordinate)
print(problem1_wind_velocity_x_coordinate, problem1_wind_velocity_y_coordinate)

[ 0.9781476   0.7313537  -0.9961947  ... -0.01745241  0.190809
 -0.30901699] [-0.20791169  0.68199836 -0.08715574 ... -0.9998477  -0.98162718
 -0.95105652]
[ 0.58688856  0.14627074 -0.09961947 ... -0.02792385  0.26713259
 -0.43262379] [-0.12474701  0.13639967 -0.00871557 ... -1.59975631 -1.37427806
 -1.33147912]


In [8]:
# Put the average wind velocity x and y coordinates here in these variables
problem1_average_wind_velocity_x_coordinate = np.mean(problem1_wind_velocity_x_coordinate)
problem1_average_wind_velocity_y_coordinate = np.mean(problem1_wind_velocity_y_coordinate)

# First calculate the angle of the average wind velocity vector in degrees
problem1_average_wind_velocity_angle_degrees = np.degrees(np.arctan2(
    problem1_average_wind_velocity_y_coordinate, problem1_average_wind_velocity_x_coordinate))
# Then calculate the average angle of the wind direction in degrees (using the wind direction in the data)
problem1_average_wind_direction_angle_degrees = np.mean(problem1_wind_direction)

# Finally, are they the same? Answer as a boolean value (True or False)
problem1_same_angle = problem1_average_wind_velocity_angle_degrees == problem1_average_wind_direction_angle_degrees

In [9]:
print(problem1_average_wind_velocity_x_coordinate, problem1_average_wind_velocity_y_coordinate)
print(problem1_average_wind_velocity_angle_degrees, problem1_average_wind_direction_angle_degrees)
print(problem1_same_angle)

-1.038909498722117 -0.3807312196610262
-159.87353002120085 192.281280627246
False


In [10]:
problem1_wind_velocity_covariance_matrix = np.cov(problem1_wind_velocity_x_coordinate,
                                                  problem1_wind_velocity_y_coordinate)
problem1_wind_velocity_covariance_matrix

array([[2.45331787, 0.06366291],
       [0.06366291, 1.89213988]])

---
## Assignment 3, PROBLEM 2
Maximum Points = 8


For this problem you will need the [pandas](https://pandas.pydata.org/) package and the [sklearn](https://scikit-learn.org/stable/) package. Inside the `data` folder from the course website you will find a file called `indoor_train.csv`, this file includes a bunch of positions in (X,Y,Z) and also a location number. The idea is to assign a room number (Location) to the coordinates (X,Y,Z).

1. [2p] Take the data in the file `indoor_train.csv` and load it using pandas into a dataframe `df_train`
2. [3p] From this dataframe `df_train`, create two numpy arrays, one `Xtrain` and `Ytrain`, they should have sizes `(1154,3)` and `(1154,)` respectively. Their `dtype` should be `float64` and `int64` respectively.
3. [3p] Train a Support Vector Classifier, `sklearn.svc.SVC`, on `Xtrain, Ytrain` with `kernel='linear'` and name the trained model `svc_train`.

To mimic how [kaggle](https://www.kaggle.com/) works, the Autograder has access to a hidden test-set and will test your fitted model.

In [11]:
df_train = pd.read_csv('data/indoor_train.csv')
df_train

Position X   Position Y  Position Z  Location
0           32.0         15.0         4.4        18
1            8.0         17.0         1.5         9
2            4.0         13.0         4.4        13
3           39.0         16.0         4.4        18
4           34.0         12.0         7.6        15
...          ...          ...         ...       ...
1149        39.0          9.0         1.5        11
1150        38.0         26.0         4.4         6
1151         4.0          7.0         1.5         2
1152        21.0         19.0         1.5        17
1153        25.0         19.0         7.6        19

[1154 rows x 4 columns]

In [12]:
Xtrain = np.array(df_train[['Position X', ' Position Y', 'Position X']].astype('float64'))
Xtrain

array([[32., 15., 32.],
       [ 8., 17.,  8.],
       [ 4., 13.,  4.],
       ...,
       [ 4.,  7.,  4.],
       [21., 19., 21.],
       [25., 19., 25.]], shape=(1154, 3))

In [13]:
Ytrain = np.array(df_train[['Location']].astype('int64')).flatten()
Ytrain

array([18,  9, 13, ...,  2, 17, 19], shape=(1154,))

In [14]:
from sklearn.svm import SVC

svc_train = SVC(kernel='linear')
svc_train.fit(Xtrain, Ytrain)

SVC(kernel='linear')

---
## Assignment 3, PROBLEM 3
Maximum Points = 8


Let us build a proportional model ($\mathbb{P}(Y=1 \mid X) = G(\beta_0+\beta \cdot X)$ where $G$ is the logistic function) for the spam vs not spam data. Here we assume that the features are presence vs not presence of a word, let $X_1,X_2,X_3$ denote the presence (1) or absence (0) of the words $("free", "prize", "win")$.

1. [2p] Load the file `data/spam.csv` and create two numpy arrays, `problem3_X` which has shape **(n_texts,3)** where each feature in `problem3_X` corresponds to $X_1,X_2,X_3$ from above, `problem3_Y` which has shape **(n_texts,)** and consists of a $1$ if the email is spam and $0$ if it is not. Split this data into a train-calibration-test sets where we have the split $40\%$, $20\%$, $40\%$, put this data in the designated variables in the code cell.

2. [2p] Follow the calculation from the lecture notes where we derive the logistic regression and implement the final loss function inside the class `ProportionalSpam`. You can use the `Test` cell to check that it gives the correct value for a test-point.

3. [2p] Train the model `problem3_ps` on the training data. The goal is to calibrate the probabilities output from the model. Start by creating a new variable `problem3_X_pred` (shape `(n_samples,1)`) which consists of the predictions of `problem3_ps` on the calibration dataset. Then train a calibration model using `sklearn.tree.DecisionTreeRegressor`, store this trained model in `problem3_calibrator`. Recall that calibration error is the following for a fixed function $f$
$$
    \sqrt{\mathbb{E}[|\mathbb{E}[Y \mid f(X)] - f(X)|^2]}.
$$

4. [2p] Use the trained model `problem3_ps` and the calibrator `problem3_calibrator` to make final predictions on the testing data, store the prediction in `problem3_final_predictions`.

In [15]:
df = pd.read_csv('data/spam.csv', encoding='latin')
df

v1  \
0      ham   
1      ham   
2     spam   
3      ham   
4      ham   
...    ...   
5567  spam   
5568   ham   
5569   ham   
5570   ham   
5571   ham   

                                                                                                                                                                     v2  \
0                                                       Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...   
1                                                                                                                                         Ok lar... Joking wif u oni...   
2           Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's   
3                                                                                                                     U dun say so early hor... U c already then say...   
4                                                                                                         Nah I don't think he goes to usf, he lives around here though   
...                                                                                                                                                                 ...   
5567  This is the 2nd time we have tried 2 contact u. U have won the å£750 Pound prize. 2 claim is easy, call 087187272008 NOW1! Only 10p per minute. BT-national-rate.   
5568                                                                                                                              Will Ì_ b going to esplanade fr home?   
5569                                                                                                          Pity, * was in mood for that. So...any other suggestions?   
5570                                      The guy did some bitching but I acted like i'd be interested in buying something else next week and he gave it to us for free   
5571                                                                                                                                         Rofl. Its true to its name   

     Unnamed: 2 Unnamed: 3 Unnamed: 4  
0           NaN        NaN        NaN  
1           NaN        NaN        NaN  
2           NaN        NaN        NaN  
3           NaN        NaN        NaN  
4           NaN        NaN        NaN  
...         ...        ...        ...  
5567        NaN        NaN        NaN  
5568        NaN        NaN        NaN  
5569        NaN        NaN        NaN  
5570        NaN        NaN        NaN  
5571        NaN        NaN        NaN  

[5572 rows x 5 columns]

In [16]:
df = df.T.head(2).T
df

v1  \
0      ham   
1      ham   
2     spam   
3      ham   
4      ham   
...    ...   
5567  spam   
5568   ham   
5569   ham   
5570   ham   
5571   ham   

                                                                                                                                                                     v2  
0                                                       Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...  
1                                                                                                                                         Ok lar... Joking wif u oni...  
2           Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's  
3                                                                                                                     U dun say so early hor... U c already then say...  
4                                                                                                         Nah I don't think he goes to usf, he lives around here though  
...                                                                                                                                                                 ...  
5567  This is the 2nd time we have tried 2 contact u. U have won the å£750 Pound prize. 2 claim is easy, call 087187272008 NOW1! Only 10p per minute. BT-national-rate.  
5568                                                                                                                              Will Ì_ b going to esplanade fr home?  
5569                                                                                                          Pity, * was in mood for that. So...any other suggestions?  
5570                                      The guy did some bitching but I acted like i'd be interested in buying something else next week and he gave it to us for free  
5571                                                                                                                                         Rofl. Its true to its name  

[5572 rows x 2 columns]

In [17]:
def get_feature(text, word):
    return 1 if word in text.lower() else 0


def get_category(text):
    return 1 if text == 'spam' else 0


df['X1'] = df['v2'].apply(lambda text: get_feature(text=text, word='free')).astype('float')
df['X2'] = df['v2'].apply(lambda text: get_feature(text=text, word='prize')).astype('float')
df['X3'] = df['v2'].apply(lambda text: get_feature(text=text, word='win')).astype('float')
df['v1'] = df['v1'].apply(get_category).astype('float')
df

v1  \
0     0.0   
1     0.0   
2     1.0   
3     0.0   
4     0.0   
...   ...   
5567  1.0   
5568  0.0   
5569  0.0   
5570  0.0   
5571  0.0   

                                                                                                                                                                     v2  \
0                                                       Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...   
1                                                                                                                                         Ok lar... Joking wif u oni...   
2           Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's   
3                                                                                                                     U dun say so early hor... U c already then say...   
4                                                                                                         Nah I don't think he goes to usf, he lives around here though   
...                                                                                                                                                                 ...   
5567  This is the 2nd time we have tried 2 contact u. U have won the å£750 Pound prize. 2 claim is easy, call 087187272008 NOW1! Only 10p per minute. BT-national-rate.   
5568                                                                                                                              Will Ì_ b going to esplanade fr home?   
5569                                                                                                          Pity, * was in mood for that. So...any other suggestions?   
5570                                      The guy did some bitching but I acted like i'd be interested in buying something else next week and he gave it to us for free   
5571                                                                                                                                         Rofl. Its true to its name   

       X1   X2   X3  
0     0.0  0.0  0.0  
1     0.0  0.0  0.0  
2     1.0  0.0  1.0  
3     0.0  0.0  0.0  
4     0.0  0.0  0.0  
...   ...  ...  ...  
5567  0.0  1.0  0.0  
5568  0.0  0.0  0.0  
5569  0.0  0.0  0.0  
5570  1.0  0.0  0.0  
5571  0.0  0.0  0.0  

[5572 rows x 5 columns]

In [18]:
problem3_X = np.array(df[['X1', 'X2', 'X3']])
problem3_Y = np.array(df['v1']).flatten()

problem3_X_train = problem3_X[:int(0.4 * len(problem3_X))]
problem3_X_calib = problem3_X[int(len(problem3_X_train)):int(len(problem3_X_train) + 0.2 * len(problem3_X))]
problem3_X_test = problem3_X[int(len(problem3_X_calib) + len(problem3_X_train)):]

problem3_Y_train = problem3_Y[:int(0.4 * len(problem3_Y))]
problem3_Y_calib = problem3_Y[int(len(problem3_Y_train)):int(len(problem3_Y_train) + 0.2 * len(problem3_X))]
problem3_Y_test = problem3_Y[int(len(problem3_Y_calib) + len(problem3_Y_train)):]

print(problem3_X_train.shape, problem3_X_calib.shape, problem3_X_test.shape, problem3_Y_train.shape,
      problem3_Y_calib.shape, problem3_Y_test.shape)

(2228, 3) (1114, 3) (2230, 3) (2228,) (1114,) (2230,)


In [19]:
class ProportionalSpam(object):
    def __init__(self):
        self.coeffs = None
        self.result = None

    # define the objective/cost/loss function we want to minimise
    def loss(self, X, Y, coeffs):
        Z = 2 * Y - 1

        nll = np.sum(np.log(1 + np.e ** (-Z * (coeffs[0] + X @ coeffs[1:]))))
        return nll / len(X)

    def fit(self, X, Y):
        import numpy as np
        from scipy import optimize

        #Use the f above together with an optimization method from scipy
        #to find the coefficients of the model
        opt_loss = lambda coeffs: self.loss(X, Y, coeffs)
        initial_arguments = np.zeros(shape=X.shape[1] + 1)
        self.result = optimize.minimize(opt_loss, initial_arguments, method='cg')
        self.coeffs = self.result.x

    def predict(self, X):
        #Use the trained model to predict Y
        if (self.coeffs is not None):
            G = lambda x: np.exp(x) / (1 + np.exp(x))
            return np.round(10 * G(
                np.dot(X, self.coeffs[1:]) + self.coeffs[0])) / 10  # This rounding is to help you with the calibration

In [20]:
from sklearn.tree import DecisionTreeRegressor

problem3_ps = ProportionalSpam()
problem3_ps.fit(problem3_X_train, problem3_Y_train)

problem3_X_pred = problem3_ps.predict(problem3_X_calib).reshape(-1, 1)

problem3_calibrator = DecisionTreeRegressor()
problem3_calibrator.fit(problem3_X_pred, problem3_Y_calib)

DecisionTreeRegressor()

In [21]:
x = problem3_ps.predict(problem3_X_test).reshape(-1, 1)
problem3_final_predictions = problem3_calibrator.predict(x)

---
#### Local Test for Assignment 3, PROBLEM 3
Evaluate cell below to make sure your answer is valid.                             You **should not** modify anything in the cell below when evaluating it to do a local test of                             your solution.
You may need to include and evaluate code snippets from lecture notebooks in cells above to make the local test work correctly sometimes (see error messages for clues). This is meant to help you become efficient at recalling materials covered in lectures that relate to this problem. Such local tests will generally not be available in the exam.

In [22]:
try:
    import numpy as np

    test_instance = ProportionalSpam()
    test_loss = test_instance.loss(np.array([[1, 0, 1], [0, 1, 1]]), np.array([1, 0]), np.array([1.2, 0.4, 0.3, 0.9]))

    assert (np.abs(test_loss - 1.2828629432232497) < 1e-6)
    print("Your loss was correct for a test point")
except:
    print("Your loss was not correct on a test point")

Your loss was correct for a test point
